### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by KdronTheShadow** [corgi-in-tights/up-we-go#2]
Would love to see a proper config with options
(or maybe i'm just dumb and couldn't find it ><)

 such as:
**{
   allowPlayersToBeLifted: True
   rocketLiftMultiplier: 2
}**

as I think it'd be a fun way to allow players to "_double jump_" in heavy quotes, or just make the mechanic is self stronger

**Comment by corgi-in-tights** [comment]
Hi there @KdronTheShadow 
I have currently taken down the mod >.< Too small overall, going to make a mod that's bigger and has a few more tweaks than just this to it.
Plans are in action for it, but it may take up to a month 😞 

Will take your issue into consideration, thanks.
